### ISSUE TITLE
Depth of CFAT

### ISSUE THREAD

**Issue by PhuTran1005** [rayabhisek123/CFAT#10]
Thank you for sharing an amazing work.

I have a small question about the depth of CFAT. When i read the main paper, in the section 5.2, you wrote that "While configuring the proposed CFAT, we put 3 DWAB and 3 SWAB in an alternative order.". I understand that have 6 Window Attention Blocks in total. But when i looked at the supp. file, in the section 1., you wrote "We take (8, 8, 8, 8, 8, 8, 8, 8) WAB units for CFAT-l, (8, 8, 8, 8, 8) for CFAT, and (8, 8, 8) for CFAT-r.", it means CFAT has 5 Window Attention Blocks. 
It's quite confused to me, can you confirm this point?

**Comment by rayabhisek123** [comment]
Thank you for pointing out. Six alternative layers is the right one and one 8 is missing in the supplementary material. You can confirm it from the official code also. We will update it in our subsequent arXiv version. Thanks.

**Comment by rayabhisek123** [comment]
If our work is really able to serve the benefit of the CV community, please be with us in expanding the reach by sharing this work and adding stars to this repo. Thank you!

**Comment by PhuTran1005** [comment]
Sure, and I hope you can release the pre-trained models and the config file (.yml) soon that help us to retraining or reproduce your  work. 
Thank you again!!!

**Comment by rayabhisek123** [comment]
Yes, we will complete the #ToDoList soon. Thank you!

**Comment by PhuTran1005** [comment]
I have one more question about training setting. You used only 250k iters for training CFAT whereas many other papers used 500k iters. Model only needs 250k iters for convergence? Have you tried with 500k iters for training, and can it improve the current performance?

**Comment by rayabhisek123** [comment]
Yeah, in some paper you can see 500k iters because they are only consider the DIV2K dataset for training with a batch size of 16. But for larger model, we consider both DIV2K and Flikr2K as training dataset with a batch size of 32. For this setting, 250k iters is enough to sufficiently converge.

**Comment by PhuTran1005** [comment]
Yeah, i understood. Thank you for your quick reply.
