### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by franillo** [rayabhisek123/CFAT#3]
Hello,

is there a setup.py file missing?

**Comment by rayabhisek123** [comment]
Thank you for pointing out. Now uploaded.

**Comment by franillo** [comment]
Thanks for uploading. However, I still get the following error:

CFAT/setup.py", line 58, in write_version_py
    with open('VERSION', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

**Comment by rayabhisek123** [comment]
This is a version error. One thing you can do, If you have implemented any image SR model before, you just put the model file over there and call it. I think everything with ho fine.
