### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by Qqsoe** [rayabhisek123/CFAT#4]
请问怎么在一台有两张gpu的电脑上复现您的代码呢

**Comment by rayabhisek123** [comment]
You can omit "CUDA_VISIBLE_DEVICES=0,1,2" or simply put "CUDA_VISIBLE_DEVICES=0"

**Comment by Qqsoe** [comment]
好的，请问您训练耗时多久

**Comment by rayabhisek123** [comment]
It depends on the configuration of the GPU and how much GPU you have chosen to run your program in parallel. For me it took around 2.5 days of time for the DF2K dataset.
