### ISSUE TITLE
Issue about python setup.py develop

### ISSUE THREAD

**Issue by jianghongcheng** [rayabhisek123/CFAT#5]
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    write_version_py()
  File "setup.py", line 58, in write_version_py
    with open('VERSION', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

**Comment by rayabhisek123** [comment]
Due to the version difference, this issue arises. After creating your environment, you can install all the packages manually, as mentioned in requirement.txt. You are probably the third one to raise this issue. Thanks.

**Comment by Qqsoe** [comment]
I also encountered the same problem. Have you solved it？

**Comment by rayabhisek123** [comment]
yes, the problem arises due to version differences. Set your Python environment and manually install all the packages in requirement.txt
