### ISSUE TITLE
There are something wrong in Table 3.

### ISSUE THREAD

**Issue by oyryrookie** [rayabhisek123/CFAT#6]
As describe in paper, "We can observe from Tab. 3 that the model gives the best performances for interval sizes 0 and 2. "

But in Table 3, the best performance for interval sizes is 4.

**Comment by rayabhisek123** [comment]
Please take a close look, you can find the value is for k=0.5. You have mistakenly observed it as I=4.

**Comment by oyryrookie** [comment]
![1](https://github.com/rayabhisek123/CFAT/assets/166804840/39f120c2-5461-421f-92d9-7a74bd7580e4)

From the paper,I know the best value for k is 0.5, what bothers me is the PSNR of I=4, is 28.72dB, which significantly exceeds PSNR of other I value as described in Table 3., and this does not match the description in the paper, "We can observe from Tab. 3 that the model gives the best performances for interval sizes 0 and 2. ", 

if there are not something wrong, could you explain why PSNR of I=4 significantly exceeds PSNR of other I value? Thank you.

**Comment by oyryrookie** [comment]
![1](https://github.com/rayabhisek123/CFAT/assets/166804840/4a198718-1dc0-4f80-a430-fdc25d63883e)
From the paper,I know the best value for k is 0.5, what bothers me is the PSNR of I=4, is 28.72dB, which significantly exceeds PSNR of other I value as described in Table 3., and this does not match the description in the paper, "We can observe from Tab. 3 that the model gives the best performances for interval sizes 0 and 2. ", 

if there are not something wrong, could you explain why PSNR of I=4 significantly exceeds PSNR of other I value? Thank you.

**Comment by oyryrookie** [comment]
![1](https://github.com/rayabhisek123/CFAT/assets/166804840/7a70be48-7592-4fc8-ad43-82436926116f)
From the ablation study of Overlapping Constant, I know the best k value is 0.5, what bothers me is why PSNR of I=4, is 28.72dB, which significantly exceeds the PSNR of other I value, and this don't match the description of the ablation study of Interval Size, " We can observe from Tab. 3 that the model gives the best performances for interval sizes 0 and 2."

Could you explain Why PSNR of I=4 significantly exceeds the PSNR of other I value? Thank you.

**Comment by rayabhisek123** [comment]
Actually this is a writing error. The value is 27.72 and wrongfully it is compiled as 28.72. I will address the all the minors in the subsequent version of the manuscript uploaded to arXiv. Thanks
