### ISSUE TITLE
移位是怎么移位的

### ISSUE THREAD

**Issue by turbowenxuan** [rayabhisek123/CFAT#7]
矩形窗口的移位和三角形的移位是从左到右、从上到下吗，和swintransformer中的shifted window不一样吗

**Comment by rayabhisek123** [comment]
For a 16 ×16 rectangular window with shift size of 8 as in swintranformer, we find only two unique patch in the whole image. But for triangular window, we find 4 unique patch instead of two. So more participation of input pixel to reproduce the output in case of triangular window compare to rectangular window.

**Comment by turbowenxuan** [comment]
抱歉刚刚看到您的回答，解决了我的疑惑，非常感谢您。我还有一个问题，在超分辨率中，训练阶段会把一个图片分为多个patch进行输入，在测试阶段要不要这么做呢，还是整张图片输进去。

**Comment by rayabhisek123** [comment]
If your model is trained on 16×16 patches, then the dimension of your pre-trained weights are also like so. Therefore, you should send the whole testing images, divide it to 16×16 patches during preprocessing and then pass through the test model.

**Comment by wangxinchao-bit** [comment]
Hello! I've previously tested HAT, which conducts inference by segmenting the image into patches and then inferring each patch individually. I found your work to be very similar. Do you have any methods to accelerate this process, enabling parallel inference and subsequent merging? How is the merging process performed to eliminate patch boundaries?

Thanks!

**Comment by rayabhisek123** [comment]
If you can see the model architecture, the triangular and rectangular window are alternatively arranged. The boundary pixel biased present in rectangular window will eliminated by the subsequent triangular window. please go thorough the paper and code thoroughly and try to visualise all. Every details I have tried to convey to the readers. Yes, I have used three more technique to enhance my results suitable for my environment, which I have not mentioned. Please read different accelerators in DL before using it in your environment. Thanks.
