### ISSUE TITLE
Issue for input

### ISSUE THREAD

**Issue by jianghongcheng** [rayabhisek123/CFAT#8]
if the input is (1,1,40,28)
how to modify your code parameter to make your network work?
RuntimeError: shape '[1, 5, 8, 3, 8, 1]' is invalid for input of size 1120

**Comment by rayabhisek123** [comment]
Thanks for your interest in our findings!!
If you want to use triangular window along side with rectangular window, you have to choose initial rectangular patch that doubled the size of rectangular window size. Then, split into smaller for triangular patch (according to the paper). If you don't want this indirect process, you can customize all the window related parameter. Feel free to ask, if you have further any doubts.

**Comment by jianghongcheng** [comment]
would you please give me an example? if the input is (1,1,40,28), what is the parameter that make your network work

**Comment by rayabhisek123** [comment]
If you want to divide an image into (1,1,40,28) chunks, it is very easy for a rectangular window shape. For triangular window, first divide the image into (1,1,40,282) rectangular chunks and then make four 2828 triangular chunks as explained in the paper. You have to update the shift sizes to [0, 14, 28, 42] as you are using a window of 28. shift interval=window size/2. Hope you understand. Thank you.

**Comment by jianghongcheng** [comment]
img_size=28,
                 patch_size=1,
                 in_chans=1,
                 embed_dim=96,
                 depths=(6, 6, 6, 6),
                 num_heads=(6, 6, 6,6 ),
                 window_size=28,
                 shift_size = (0, 14,28,42),  #changed to tuple
                 interval=(0, 14),

I got the issue   

shift_size=shift_size[i],
IndexError: tuple index out of range

would you please let me how to solove it?
