### ISSUE TITLE
 would you please give me an example? if the input is (1,1,40,28), what is the parameter that make your network work

### ISSUE THREAD

**Issue by jianghongcheng** [rayabhisek123/CFAT#9]
would you please give me an example? if the input is (1,1,40,28), what is the parameter that make your network work

**Comment by rayabhisek123** [comment]
If you want to divide an image into (1,1,40,28) chunks, it is very easy for a rectangular window shape. For triangular window, first divide the image into  (1,1,40,28*2) rectangular chunks and then make four 28*28 triangular chunks as explained in the paper. You have to update the shift sizes to [0, 14, 28, 42] as you are using a window of 28. shift interval=window size/2. Hope you understand. Thank you.

**Comment by jianghongcheng** [comment]
Your code is still not working

     
 img_size=28,
             patch_size=1,
             in_chans=1,
             embed_dim=96,
             depths=(6, 6, 6, 6),
             num_heads=(6, 6, 6,6 ),
             window_size=28,
             shift_size = (0, 14,28,42),  #changed to tuple
             interval=(0, 14),
I got the issue

shift_size=shift_size[i],
IndexError: tuple index out of range

would you please let me how to solove it?

**Comment by PhuTran1005** [comment]
I think here isn't the newest code, i realized some module is different from those in the paper.
